import React, { useState} from "react";
import styles from "./Body_TermsAndServices.module.css";

export default function Body_TermsAndServices(){

    return(
        <main>
            <header className={styles.title}>
                Terms and Services
            </header>

            <h2 className={styles.align}>
            Welcome to Finch Limited Company

            </h2>

            <p className={styles.align}>
            By using our website, you agree to comply with and be bound by the following terms and conditions.
            Please read them carefully.
            </p>

            <ol>
                <li className={styles.paragraph}>
                    <strong>
                    Acceptance of Terms
                    </strong><br />
                    By accessing and using this website, you agree to abide by these terms.
                    If you do not agree, please do not use the website.
                </li>
                <li className={styles.paragraph}>
                    <strong>
                    Use of the Website
                    </strong><br />
                    You must use the website for lawful purposes only.
                    You agree not to disrupt or attempt to compromise the website’s security or functionality.
                </li>
                <li className={styles.paragraph}>
                    <strong>
                    Intellectual Property
                    </strong><br />
                    All content on this website, including text, images, graphics, and logos,
                    is the property of Finch Limited Company unless otherwise stated.
                    You may not copy, reproduce, or distribute content without explicit permission.
                </li>
                <li className={styles.paragraph}>
                    <strong>
                    User-Submitted Content
                    </strong><br />
                    Any content you submit (e.g., comments, reviews)
                    must not violate any laws or infringe third-party rights.
                    By submitting content, you grant us the right to use, modify, or display it as needed.
                </li>
                <li className={styles.paragraph}>
                    <strong>
                    Limitation of LiabilityF
                    </strong><br />
                    inch Limited Company is not liable for any damages
                    arising from the use or inability to use the website.
                    We do not guarantee that the website will be error-free, secure, or uninterrupted.
                </li>
                <li className={styles.paragraph}>
                    <strong>
                    External Links
                    </strong><br />
                    Our website may contain links to third-party websites.
                    We are not responsible for the content or privacy practices of these sites.
                </li>
                <li className={styles.paragraph}>
                    <strong>
                    Termination
                    </strong><br />
                    We reserve the right to suspend or terminate your access to the
                    website for violating these terms or engaging in prohibited conduct.
                </li>
                <li className={styles.paragraph}>
                    <strong>
                    Changes to Terms
                    </strong><br />
                    We may update these terms from time to time.
                    Continued use of the website signifies acceptance of updated terms.
                </li>
                <li className={styles.paragraph}>
                    <strong>
                    Governing Law
                    </strong><br />
                    These terms and conditions are governed by the laws of Greece.
                    Any disputes will be resolved in the courts of Thessaloniki.
                </li>
            </ol>

            <p className={styles.align}>
            <em>
                Text generated by ChatGPT
            </em>
            </p>
        </main>
    );

}